branch-defaults:
  schools:
    environment: collabrooms-prod-env
environment-defaults:
  collabrooms-prod-env:
    branch: null
    repository: null
global:
  application_name: collabrooms-prod
  default_ec2_keyname: null
  default_platform: Python 3.6 running on 64bit Amazon Linux
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
