# Generated by Django 3.0.7 on 2020-06-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='zoom_url',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
