# Generated by Django 2.1.1 on 2020-11-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='refresh_token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
