# Generated by Django 2.1.1 on 2020-09-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='test',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
