# Generated by Django 3.0.7 on 2020-06-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0002_room_zoom_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zoom_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='meeting_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
