# Generated by Django 2.1.1 on 2020-09-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0002_token_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='classes',
            field=models.CharField(max_length=1000),
        ),
    ]
