# Generated by Django 2.1.1 on 2020-09-10 18:37

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0003_auto_20200910_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='classes',
            field=jsonfield.fields.JSONField(),
        ),
    ]
