# Generated by Django 3.0.7 on 2020-06-24 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0003_auto_20200623_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
