# Generated by Django 3.0.7 on 2020-07-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0004_auto_20200624_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
            ],
        ),
    ]
