# Generated by Django 3.0.7 on 2020-07-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0005_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='course',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
