# Generated by Django 3.0.8 on 2020-07-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0006_room_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='section',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
