# Generated by Django 3.0.8 on 2020-08-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0007_profile_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img_url',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
