# Generated by Django 3.0.8 on 2020-08-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0007_profile_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='first_login',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
