# Generated by Django 3.0.8 on 2020-08-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0008_auto_20200811_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
    ]
