# Generated by Django 3.0.7 on 2020-08-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0008_auto_20200811_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='notes',
            field=models.CharField(default='Text', max_length=50000),
            preserve_default=False,
        ),
    ]
