# Generated by Django 3.0.8 on 2020-08-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0008_profile_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='img_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
