# Generated by Django 3.0.7 on 2020-08-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0009_room_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='notes',
            field=models.TextField(max_length=50000),
        ),
    ]
