# Generated by Django 3.0.8 on 2020-08-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0009_auto_20200803_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
