# Generated by Django 3.0.8 on 2020-08-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0009_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
