# Generated by Django 3.0.7 on 2020-08-19 21:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0010_auto_20200819_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='notes',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
