# Generated by Django 3.0.8 on 2020-08-12 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0010_room_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='visible',
        ),
    ]
