# Generated by Django 2.1.1 on 2020-08-22 15:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0011_auto_20200819_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='notes',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
