# Generated by Django 2.1.5 on 2020-09-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0012_auto_20200822_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
