# Generated by Django 2.1.5 on 2020-09-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0013_auto_20200905_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=45),
        ),
    ]
