# Generated by Django 3.1 on 2020-09-08 20:31

from django.db import migrations, models
import jsonfield.fields



class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0014_auto_20200905_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='classes',
            field=jsonfield.fields.JSONField(default={'class': []}),
            preserve_default=False,
        ),
    ]
