# Generated by Django 3.1 on 2020-09-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0015_profile_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='isSection',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
