# Generated by Django 3.1 on 2020-09-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0016_section_issection'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(default='columbia', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='school',
            field=models.CharField(default='columbia', max_length=100),
            preserve_default=False,
        ),
    ]
