# Generated by Django 3.1.1 on 2020-09-09 04:34

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0016_section_issection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='classes',
            field=jsonfield.fields.JSONField(),
        ),
    ]
