# Generated by Django 3.1 on 2020-09-10 14:55

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0017_auto_20200910_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='classes',
            field=jsonfield.fields.JSONField(),
        ),
    ]
