# Generated by Django 2.1.1 on 2020-09-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0018_auto_20200910_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='count',
            field=models.IntegerField(default=4000),
            preserve_default=False,
        ),
    ]
